import {Inter} from 'next/font/google'
import {ReactNode} from "react";
import "../style/globals.scss"
import {LayoutMain} from "@/widgets";

const inter = Inter({subsets: ['latin']})

export const metadata = {
    title: 'App',
    description: 'Generated by create next app',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: ReactNode
}) {
    return (
        <html lang="en">
        <body className={inter.className}>
        <LayoutMain>
            {children}
        </LayoutMain>
        </body>
        </html>
    )
}
